services:
  - type: web
    name: fixit-dncc
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fixit-dncc-db
          property: connectionString

databases:
  - name: fixit-dncc-db
    plan: free
    region: singapore
    databaseName: fixit_dncc
    user: fixit_admin
